# Generated by Django 5.1.3 on 2024-11-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
