# Generated by Django 5.1.3 on 2024-11-22 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='end_record_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 12, 0)),
        ),
        migrations.AddField(
            model_name='record',
            name='start_record_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 12, 0)),
        ),
    ]
