# Generated by Django 5.1.3 on 2024-11-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_record_end_record_time_record_start_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='end_record_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='start_record_time',
            field=models.DateTimeField(),
        ),
    ]
