# Generated by Django 5.1.3 on 2024-11-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='end_record_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='start_record_time',
            field=models.DateTimeField(null=True),
        ),
    ]
