# Generated by Django 5.1.3 on 2024-11-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_employee_status_archiverecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiverecord',
            name='employee',
            field=models.CharField(max_length=150),
        ),
    ]
