# Generated by Django 5.1.3 on 2024-11-22 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_archiverecord_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiverecord',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_records', to='app.employee'),
        ),
    ]
