# Generated by Django 5.1.3 on 2024-11-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_archiverecord_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pay_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
