# Generated by Django 5.1.3 on 2024-11-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_employee_pay_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiverecord',
            name='start_record_time',
            field=models.DateTimeField(null=True),
        ),
    ]
